previewsEnabled: true
services:
  - type: web
    name: highways-search
    repo: https://github.com/imaginerio/imaginerioSearch.git
    region: oregon
    env: node
    healthCheckPath: /layers
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - fromGroup: tile-generator
      - key: DATABASE
        value: HighwaysWaterways_Data
      - key: DB_URL
        fromDatabase:
          name: highways
          property: connectionString
  - type: cron
    name: highways-database-seeder
    region: oregon
    repo: https://github.com/imaginerio/imaginerioSearch.git
    env: node
    buildCommand: yarn
    startCommand: yarn db:job
    schedule: "1 0 * * 6" 
    envVars:
      - fromGroup: tile-generator
      - fromGroup: highways-search
      - key: DATABASE
        value: HighwaysWaterways_Data
      - key: DB_URL
        fromDatabase:
          name: highways
          property: connectionString
  - type: cron
    name: highways-vector-tile-generator
    region: oregon
    env: docker
    schedule: "1 0 * * 6" 
    repo: https://github.com/imaginerio/vector-tile-generator.git
    branch: highways
    envVars:
      - key: AWS_BUCKET
        value: s3://highwaystiles/base/{z}/{x}/{y}?timeout=10000
      - key: OMIT
        value: '["BuildingsPoly", "PrecipitationPoint", "ImmigrantBusinessPoint", "Complains311Point", "ChemicalCompositionPoint", "SocioeconomicPoly", "SeaLevelRisePoly", "OverallPoly", "MinorityStatusPoly", "HousingPoly", "HouseholdPoly", "FloodPoly"]'
      - fromGroup: tile-generator
databases:
  - name: highways
