previewsEnabled: true
services:
  - type: web
    name: highways-search
    repo: https://github.com/imaginerio/imaginerioSearch.git
    region: oregon
    env: node
    healthCheckPath: /layers
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - fromGroup: tile-generator
      - key: DATABASE
        value: HighwaysWaterways_Data
      - key: OMIT
        value: '["PrecipitationPoint", "ImmigrantBusinessPoint", "Complains311Point", "ChemicalCompositionPoint", "SocioeconomicPoly", "SeaLevelRisePoly", "OverallPoly", "MinorityStatusPoly", "HousingPoly", "HouseholdPoly", "FloodPoly"]'
      - key: DB_URL
        fromDatabase:
          name: highways
          property: connectionString
  - type: cron
    name: highways-database-seeder
    region: oregon
    repo: https://github.com/imaginerio/imaginerioSearch.git
    env: node
    buildCommand: yarn
    startCommand: yarn db:job
    schedule: "1 0 * * 6" 
    envVars:
      - fromGroup: tile-generator
      - fromGroup: highways-search
      - key: DATABASE
        value: HighwaysWaterways_Data
      - key: OMIT
        value: '["PrecipitationPoint", "ImmigrantBusinessPoint", "Complains311Point", "ChemicalCompositionPoint", "SocioeconomicPoly", "SeaLevelRisePoly", "OverallPoly", "MinorityStatusPoly", "HousingPoly", "HouseholdPoly", "FloodPoly"]'
      - key: DB_URL
        fromDatabase:
          name: highways
          property: connectionString
  - type: cron
    name: highways-vector-tile-generator
    region: oregon
    env: docker
    schedule: "1 0 * * 6" 
    repo: https://github.com/imaginerio/vector-tile-generator.git
    branch: highways
    envVars:
      - fromGroup: tile-generator
      - key: STEP
        value: 2000
      - key: AWS_BUCKET
        value: s3://highwaystiles/base/{z}/{x}/{y}?timeout=10000
      - key: DATABASE
        value: HighwaysWaterways_Data
      - key: OMIT
        value: '["PrecipitationPoint", "ImmigrantBusinessPoint", "Complains311Point", "ChemicalCompositionPoint", "SocioeconomicPoly", "SeaLevelRisePoly", "OverallPoly", "MinorityStatusPoly", "HousingPoly", "HouseholdPoly", "FloodPoly"]'
  - type: cron
    name: highways-image-generator
    region: oregon
    env: docker
    schedule: "1 0 * * 6" 
    repo: https://github.com/Spatial-Studies-Lab/image-processor.git
    branch: main
    envVars:
      - fromGroup: tile-generator
      - fromGroup: sendgrid
      - key: BUCKET_TARGET
        value: highwayswaterways-images
      - key: BUCKET_SOURCE
        value: connector-highwayswaterways-images
      - key: EMAIL
        value: dave@axismaps.com
      - key: PROJECT
        value: highways-waterways
      - key: TASK
        value: image
databases:
  - name: highways
